# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bored-together' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bored-together
  pod 'Apollo'
  pod 'Firebase/Auth'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'lottie-ios'
  pod 'TinderSwipeView’ , '~> 1.1.8'

end
